kind: Template
apiVersion: v1
labels:
  template: elasticstack-secret-template
metadata:
  name: elasticstack-secret-template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${ELASTIC_NAME}-${INSTANCE}-credentials
    stringData:
      username: ${USERNAME}
      password: ${PASSWORD}
    type: kubernetes.io/basic-auth

  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${KIBANA_NAME}-${INSTANCE}-encryption-key
    stringData:
      encryptionkey: ${ENCRYPTION_KEY}
    type: Opaque
parameters:
  - name: ELASTIC_NAME
    description: Elasticsearch application name
    displayName: Elasticsearch application name
    required: true
    value: elasticsearch
  - name: KIBANA_NAME
    description: Kibana application name
    displayName: Kibana application name
    required: true
    value: kibana
  - name: INSTANCE
    description: The deployment instance name
    displayName: Deployment Instance
    required: true
    value: master
  - name: USERNAME
    description: User name
    displayName: User name
    required: true
    value: elastic
  - name: PASSWORD
    description: Password
    displayName: Password
    generate: expression
    from: "[a-zA-Z]{1}[a-zA-Z0-9]{20}[a-zA-Z]{1}"
  - name: ENCRYPTION_KEY
    description: Encryption Key
    displayName: Encryption Key
    generate: expression
    from: "[a-zA-Z]{1}[a-zA-Z0-9]{48}[a-zA-Z]{1}"
